name: "Nightly Build"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'  # 21:00 UTC == 24:00 Israel time


jobs:

  Determine_Runnable_Jobs:
    runs-on: ubuntu-latest
    outputs:
      jobs_to_run: ${{ steps.script.outputs.string }}
    steps:
      - name: Clone Lithops repository
        uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Determine which jobs to run
        id: script
        run: |
          value=$(python3 ./lithops/scripts/check_job_on_list.py "${GITHUB_WORKFLOW}")
          echo "::set-output name=string::$value"



  CE_COS:

    runs-on: ubuntu-latest

    needs: Determine_Runnable_Jobs
    if: contains(needs.Determine_Runnable_Jobs.outputs.jobs_to_run,'CE_COS') #${{github.job}}

    steps:
      - name: Clone Lithops repository
        uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        run: |
          python3 setup.py develop
      - name: install secrets in lithops config
        run: python3 ./lithops/scripts/config_fill_secrets.py "CE_COS" "${GITHUB_ACTOR,,}" "${{secrets.IAMAPIKEY }}" "${{secrets.COS_API_KEY }}"

      - name: build new runtime
        env:
            LITHOPS_CONFIG_FILE: ${{ github.workspace }}/lithops/tests/config_files/lithops_config_CE_COS.yaml
        run: |
         docker login -u cohenjomer -p "${{ secrets.DOCKER_TOKEN }}"
         cd runtime/code_engine
         lithops runtime build cohenjomer/lithops-ce-"${GITHUB_ACTOR,,}" -b code_engine

      - name: Run Python tests
        run: |
         lithops test -c lithops/tests/config_files/lithops_config_CE_COS.yaml


  CF_COS:
    runs-on: ubuntu-latest

    needs: Determine_Runnable_Jobs
    if: contains(needs.Determine_Runnable_Jobs.outputs.jobs_to_run,'CF_COS') #${{github.job}}

    steps:
      - name: Clone Lithops repository
        uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        run: |
          python3 setup.py develop
      - name: install secrets in lithops config
        run: python3 ./lithops/scripts/config_fill_secrets.py "CF_COS" "${GITHUB_ACTOR,,}" "${{ secrets.IAMAPIKEY }}" "${{ secrets.COS_API_KEY }}" "${{ secrets.CF_API_KEY }}"

      - name: build new runtime
        env:
          LITHOPS_CONFIG_FILE: ${{ github.workspace }}/lithops/tests/config_files/lithops_config_CF_COS.yaml
        run: |
          docker login -u cohenjomer -p "${{ secrets.DOCKER_TOKEN }}"
          cd runtime/ibm_cf
          lithops runtime build -f Dockerfile.python38 cohenjomer/lithops-cf-"${GITHUB_ACTOR,,}"

      - name: Run Python tests
        run: |
          lithops test -c lithops/tests/config_files/lithops_config_CF_COS.yaml


  Clean:
    runs-on: ubuntu-latest
    if: always()  # this job will run regardless of the above job's status.
    needs: [CE_COS,CF_COS]

    steps:
      - name: Clone Lithops repository
        uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        run: |
          python3 setup.py develop

      - name: Clean storage
        run: lithops clean








